[package]
name = "arem"
description = "A Rust crate for creating WebP video thumbnails powered by FFmpeg."
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
